### ISSUE TITLE
ME 페이지가 정상작동하지 않습니다!

### ISSUE THREAD

**Issue by JongCo** [GuitarCoders/front#6]
누구의 문제인지 파악하려고 코드를 보고있는데 하나도 모르겟습니다 next.js의 세계.. 그래서 일단 이렇게 남겨봅니다.

에러가 난 곳의 스크린샷을 함께 첨부합니다.
<img width="720" alt="스크린샷 2023-07-21 오후 3 05 47" src="https://github.com/GuitarCoders/front/assets/50693467/7bbde21e-2d15-4e2d-b420-ff486341fa04">

**Comment by KeMezz** [comment]
## 첫 번째, `_id` 못 찾는 오류

`_id`를 못 찾는 문제는 현재 SSR로 user 정보를 받아오는 일부 페이지(/me 포함)에서, 현재 백엔드에서 friends 배열을 보내주지 않고 있다는 사실에 대해 대응하지 않고 있는 탓에 결국 user 객체 전체를 undefined로 돌려받게되어, Next.js 상에서 페이지를 만들면서 오류가 발생하는 것이 원인이었습니다. 해당 문제는 [friends를 참조하는 모든 코드를 임시로 주석 처리하여 해결](ab4c741ea2ef52e7ef7e2c0b605d76933943c0f7)하였습니다.


## 두 번째, getPosts 오류 

<img width="417" alt="image" src="https://github.com/GuitarCoders/front/assets/88423849/885fb73e-537c-4a4b-bfe2-18b323e521ef">

또한, 1번 문제가 해결된 이후에도 GraphQL 호출 문법에서 타입명을 제대로 명시하지 않아서 getPosts 요청에 오류가 발생했었습니다. [API 명세와 일치하는 타입명으로 요청하도록 수정하여 대응](b706b95f13aa9b2c1343845bdc9978a865494be7)하였습니다.
